services:
  bank:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - bank_data:/app/data
    command: >
      /bin/bash -lc "
      mkdir -p /app/data &&
      touch /app/data/sessions.dat /app/data/balances.dat /app/data/accounts.dat /app/data/qris_transaction.dat &&
      /opt/apache-tomcat-8.5.96/bin/catalina.sh run
      "
    restart: unless-stopped

volumes:
  bank_data:

