ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER bank IDENTIFIED BY bank;
GRANT CONNECT, RESOURCE TO bank;

ALTER SESSION SET CURRENT_SCHEMA = bank;

CREATE TABLE accounts (
    account_id VARCHAR2(10) PRIMARY KEY,
    balance NUMBER(12,2)
    pass_hash RAW (256)
);

COMMIT;